export const translate: any = {
    id: "Mã",
    createdAt: "Ngày tạo",
    description: "Mô tả",
    name: "Tên",
    priceUnit: "Đơn giá",
    quantity: "Số lượng",
    total: "Tổng số",
    bankAccount: "Tài khoản ngân hàng",
    date: "Ngày",
    paymentMethod: "Phương thức thanh toán",
    staff: "Nhân viên",
    manager: "Quản lý",
    month: "Tháng",
    year: "Năm",
};
